name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: temurin

      - name: Set API YML
        run: |
          echo "${{ secrets.API_SERVER_YML }}" | base64 --decode > api-server/src/main/resources/application-api-prod.yml

      - name: Set CHATTING YML
        run: |
          echo "${{ secrets.CHATTING_SERVER_YML }}" | base64 --decode > chatting-server/src/main/resources/application-chatting-prod.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build API-SERVER
        run: ./gradlew api-server:build -x test

      - name: Build CHATTING-SERVER
        run: ./gradlew chatting-server:build -x test


        # 디렉토리 생성
      - name: Make Directory
        run: mkdir -p deploy

      # Jar 파일 복사
      - name: Copy Jar
        run: |
          cp ./api-server/build/libs/*.jar ./deploy
          cp ./chatting-server/build/libs/*.jar ./deploy

      # appspec.yml 파일 복사
      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      # script files 복사
      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

      - name: Make zip file
        run: zip -r ./lastone.zip ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./lastone.zip s3://lastone-image-bucket/lastone.zip

      # Deploy
      - name: Deploy
        run: |
          aws deploy create-deployment \
            --application-name lastone \
            --deployment-group-name lastone-group \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --file-exists-behavior OVERWRITE \
            --s3-location bucket=lastone-image-bucket,bundleType=zip,key=lastone.zip \